{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "3b918c36",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "Requirement already satisfied: arcgis in c:\\users\\hp\\appdata\\roaming\\python\\python39\\site-packages (2.0.1)\n",
      "Requirement already satisfied: requests>=1.27.1 in c:\\programdata\\anaconda3\\lib\\site-packages (from arcgis) (2.28.1)\n",
      "Requirement already satisfied: pandas>=1.3.5 in c:\\programdata\\anaconda3\\lib\\site-packages (from arcgis) (1.4.4)\n",
      "Requirement already satisfied: geomet in c:\\users\\hp\\appdata\\roaming\\python\\python39\\site-packages (from arcgis) (0.3.0)\n",
      "Requirement already satisfied: requests-negotiate-sspi in c:\\users\\hp\\appdata\\roaming\\python\\python39\\site-packages (from arcgis) (0.5.2)\n",
      "Requirement already satisfied: ipywidgets>=7 in c:\\programdata\\anaconda3\\lib\\site-packages (from arcgis) (7.6.5)\n",
      "Requirement already satisfied: jupyterlab in c:\\programdata\\anaconda3\\lib\\site-packages (from arcgis) (3.4.4)\n",
      "Requirement already satisfied: pyshp>=2 in c:\\users\\hp\\appdata\\roaming\\python\\python39\\site-packages (from arcgis) (2.3.1)\n",
      "Requirement already satisfied: six in c:\\users\\hp\\appdata\\roaming\\python\\python39\\site-packages (from arcgis) (1.15.0)\n",
      "Requirement already satisfied: numpy>=1.16.2 in c:\\users\\hp\\appdata\\roaming\\python\\python39\\site-packages (from arcgis) (1.19.5)\n",
      "Requirement already satisfied: urllib3 in c:\\programdata\\anaconda3\\lib\\site-packages (from arcgis) (1.26.11)\n",
      "Requirement already satisfied: ujson>=3 in c:\\programdata\\anaconda3\\lib\\site-packages (from arcgis) (5.4.0)\n",
      "Requirement already satisfied: winkerberos in c:\\users\\hp\\appdata\\roaming\\python\\python39\\site-packages (from arcgis) (0.9.0)\n",
      "Requirement already satisfied: cryptography in c:\\programdata\\anaconda3\\lib\\site-packages (from arcgis) (37.0.1)\n",
      "Requirement already satisfied: requests-oauthlib in c:\\users\\hp\\appdata\\roaming\\python\\python39\\site-packages (from arcgis) (1.3.1)\n",
      "Requirement already satisfied: cachetools in c:\\users\\hp\\appdata\\roaming\\python\\python39\\site-packages (from arcgis) (5.2.0)\n",
      "Requirement already satisfied: pywin32>=223 in c:\\programdata\\anaconda3\\lib\\site-packages (from arcgis) (302)\n",
      "Requirement already satisfied: requests-ntlm in c:\\users\\hp\\appdata\\roaming\\python\\python39\\site-packages (from arcgis) (1.1.0)\n",
      "Requirement already satisfied: requests-kerberos in c:\\users\\hp\\appdata\\roaming\\python\\python39\\site-packages (from arcgis) (0.14.0)\n",
      "Requirement already satisfied: matplotlib in c:\\programdata\\anaconda3\\lib\\site-packages (from arcgis) (3.5.2)\n",
      "Requirement already satisfied: requests-toolbelt in c:\\users\\hp\\appdata\\roaming\\python\\python39\\site-packages (from arcgis) (0.10.0)\n",
      "Requirement already satisfied: widgetsnbextension>=3 in c:\\programdata\\anaconda3\\lib\\site-packages (from arcgis) (3.5.2)\n",
      "Requirement already satisfied: keyring>=23.3.* in c:\\programdata\\anaconda3\\lib\\site-packages (from arcgis) (23.4.0)\n",
      "Requirement already satisfied: python-certifi-win32 in c:\\users\\hp\\appdata\\roaming\\python\\python39\\site-packages (from arcgis) (1.6.1)\n",
      "Requirement already satisfied: lerc in c:\\users\\hp\\appdata\\roaming\\python\\python39\\site-packages (from arcgis) (0.1.0)\n",
      "Requirement already satisfied: notebook in c:\\programdata\\anaconda3\\lib\\site-packages (from arcgis) (6.4.12)\n",
      "Requirement already satisfied: lxml in c:\\programdata\\anaconda3\\lib\\site-packages (from arcgis) (4.9.1)\n",
      "Requirement already satisfied: jupyter-client<=6.1.12 in c:\\users\\hp\\appdata\\roaming\\python\\python39\\site-packages (from arcgis) (6.1.12)\n",
      "Requirement already satisfied: requests-gssapi in c:\\users\\hp\\appdata\\roaming\\python\\python39\\site-packages (from arcgis) (1.2.3)\n",
      "Requirement already satisfied: traitlets>=4.3.1 in c:\\programdata\\anaconda3\\lib\\site-packages (from ipywidgets>=7->arcgis) (5.1.1)\n",
      "Requirement already satisfied: ipython-genutils~=0.2.0 in c:\\programdata\\anaconda3\\lib\\site-packages (from ipywidgets>=7->arcgis) (0.2.0)\n",
      "Requirement already satisfied: nbformat>=4.2.0 in c:\\programdata\\anaconda3\\lib\\site-packages (from ipywidgets>=7->arcgis) (5.5.0)\n",
      "Requirement already satisfied: ipython>=4.0.0 in c:\\programdata\\anaconda3\\lib\\site-packages (from ipywidgets>=7->arcgis) (7.31.1)\n",
      "Requirement already satisfied: ipykernel>=4.5.1 in c:\\programdata\\anaconda3\\lib\\site-packages (from ipywidgets>=7->arcgis) (6.15.2)\n",
      "Requirement already satisfied: jupyterlab-widgets>=1.0.0 in c:\\programdata\\anaconda3\\lib\\site-packages (from ipywidgets>=7->arcgis) (1.0.0)\n",
      "Requirement already satisfied: tornado>=4.1 in c:\\programdata\\anaconda3\\lib\\site-packages (from jupyter-client<=6.1.12->arcgis) (6.1)\n",
      "Requirement already satisfied: jupyter-core>=4.6.0 in c:\\programdata\\anaconda3\\lib\\site-packages (from jupyter-client<=6.1.12->arcgis) (4.11.1)\n",
      "Requirement already satisfied: python-dateutil>=2.1 in c:\\programdata\\anaconda3\\lib\\site-packages (from jupyter-client<=6.1.12->arcgis) (2.8.2)\n",
      "Requirement already satisfied: pyzmq>=13 in c:\\programdata\\anaconda3\\lib\\site-packages (from jupyter-client<=6.1.12->arcgis) (23.2.0)\n",
      "Requirement already satisfied: importlib-metadata>=3.6 in c:\\programdata\\anaconda3\\lib\\site-packages (from keyring>=23.3.*->arcgis) (4.11.3)\n",
      "Requirement already satisfied: pywin32-ctypes!=0.1.0,!=0.1.1 in c:\\programdata\\anaconda3\\lib\\site-packages (from keyring>=23.3.*->arcgis) (0.2.0)\n",
      "Requirement already satisfied: pytz>=2020.1 in c:\\programdata\\anaconda3\\lib\\site-packages (from pandas>=1.3.5->arcgis) (2022.1)\n",
      "Requirement already satisfied: charset-normalizer<3,>=2 in c:\\programdata\\anaconda3\\lib\\site-packages (from requests>=1.27.1->arcgis) (2.0.4)\n",
      "Requirement already satisfied: idna<4,>=2.5 in c:\\programdata\\anaconda3\\lib\\site-packages (from requests>=1.27.1->arcgis) (3.3)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in c:\\programdata\\anaconda3\\lib\\site-packages (from requests>=1.27.1->arcgis) (2022.9.14)\n",
      "Requirement already satisfied: prometheus-client in c:\\programdata\\anaconda3\\lib\\site-packages (from notebook->arcgis) (0.14.1)\n",
      "Requirement already satisfied: nbconvert>=5 in c:\\programdata\\anaconda3\\lib\\site-packages (from notebook->arcgis) (6.4.4)\n",
      "Requirement already satisfied: Send2Trash>=1.8.0 in c:\\programdata\\anaconda3\\lib\\site-packages (from notebook->arcgis) (1.8.0)\n",
      "Requirement already satisfied: nest-asyncio>=1.5 in c:\\programdata\\anaconda3\\lib\\site-packages (from notebook->arcgis) (1.5.5)\n",
      "Requirement already satisfied: terminado>=0.8.3 in c:\\programdata\\anaconda3\\lib\\site-packages (from notebook->arcgis) (0.13.1)\n",
      "Requirement already satisfied: argon2-cffi in c:\\programdata\\anaconda3\\lib\\site-packages (from notebook->arcgis) (21.3.0)\n",
      "Requirement already satisfied: jinja2 in c:\\programdata\\anaconda3\\lib\\site-packages (from notebook->arcgis) (2.11.3)\n",
      "Requirement already satisfied: cffi>=1.12 in c:\\programdata\\anaconda3\\lib\\site-packages (from cryptography->arcgis) (1.15.1)\n",
      "Requirement already satisfied: click in c:\\programdata\\anaconda3\\lib\\site-packages (from geomet->arcgis) (8.0.4)\n",
      "Requirement already satisfied: nbclassic in c:\\programdata\\anaconda3\\lib\\site-packages (from jupyterlab->arcgis) (0.3.5)\n",
      "Requirement already satisfied: packaging in c:\\programdata\\anaconda3\\lib\\site-packages (from jupyterlab->arcgis) (21.3)\n",
      "Requirement already satisfied: jupyter-server~=1.16 in c:\\programdata\\anaconda3\\lib\\site-packages (from jupyterlab->arcgis) (1.18.1)\n",
      "Requirement already satisfied: jupyterlab-server~=2.10 in c:\\programdata\\anaconda3\\lib\\site-packages (from jupyterlab->arcgis) (2.10.3)\n",
      "Requirement already satisfied: pillow>=6.2.0 in c:\\programdata\\anaconda3\\lib\\site-packages (from matplotlib->arcgis) (9.2.0)\n",
      "Requirement already satisfied: fonttools>=4.22.0 in c:\\programdata\\anaconda3\\lib\\site-packages (from matplotlib->arcgis) (4.25.0)\n",
      "Requirement already satisfied: cycler>=0.10 in c:\\programdata\\anaconda3\\lib\\site-packages (from matplotlib->arcgis) (0.11.0)\n",
      "Requirement already satisfied: kiwisolver>=1.0.1 in c:\\programdata\\anaconda3\\lib\\site-packages (from matplotlib->arcgis) (1.4.2)\n",
      "Requirement already satisfied: pyparsing>=2.2.1 in c:\\programdata\\anaconda3\\lib\\site-packages (from matplotlib->arcgis) (3.0.9)\n",
      "Requirement already satisfied: setuptools-scm in c:\\users\\hp\\appdata\\roaming\\python\\python39\\site-packages (from python-certifi-win32->arcgis) (7.0.5)\n",
      "Requirement already satisfied: wrapt>=1.10.4 in c:\\users\\hp\\appdata\\roaming\\python\\python39\\site-packages (from python-certifi-win32->arcgis) (1.12.1)\n",
      "Requirement already satisfied: gssapi in c:\\users\\hp\\appdata\\roaming\\python\\python39\\site-packages (from requests-gssapi->arcgis) (1.8.1)\n",
      "Requirement already satisfied: pyspnego[kerberos] in c:\\users\\hp\\appdata\\roaming\\python\\python39\\site-packages (from requests-kerberos->arcgis) (0.6.0)\n",
      "Requirement already satisfied: pypiwin32>=223 in c:\\users\\hp\\appdata\\roaming\\python\\python39\\site-packages (from requests-negotiate-sspi->arcgis) (223)\n",
      "Requirement already satisfied: ntlm-auth>=1.0.2 in c:\\users\\hp\\appdata\\roaming\\python\\python39\\site-packages (from requests-ntlm->arcgis) (1.5.0)\n",
      "Requirement already satisfied: oauthlib>=3.0.0 in c:\\users\\hp\\appdata\\roaming\\python\\python39\\site-packages (from requests-oauthlib->arcgis) (3.2.2)\n",
      "Requirement already satisfied: pycparser in c:\\programdata\\anaconda3\\lib\\site-packages (from cffi>=1.12->cryptography->arcgis) (2.21)\n",
      "Requirement already satisfied: zipp>=0.5 in c:\\programdata\\anaconda3\\lib\\site-packages (from importlib-metadata>=3.6->keyring>=23.3.*->arcgis) (3.8.0)\n",
      "Requirement already satisfied: debugpy>=1.0 in c:\\programdata\\anaconda3\\lib\\site-packages (from ipykernel>=4.5.1->ipywidgets>=7->arcgis) (1.5.1)\n",
      "Requirement already satisfied: matplotlib-inline>=0.1 in c:\\programdata\\anaconda3\\lib\\site-packages (from ipykernel>=4.5.1->ipywidgets>=7->arcgis) (0.1.6)\n",
      "Requirement already satisfied: psutil in c:\\programdata\\anaconda3\\lib\\site-packages (from ipykernel>=4.5.1->ipywidgets>=7->arcgis) (5.9.0)\n",
      "Requirement already satisfied: backcall in c:\\programdata\\anaconda3\\lib\\site-packages (from ipython>=4.0.0->ipywidgets>=7->arcgis) (0.2.0)\n",
      "Requirement already satisfied: pygments in c:\\programdata\\anaconda3\\lib\\site-packages (from ipython>=4.0.0->ipywidgets>=7->arcgis) (2.11.2)\n",
      "Requirement already satisfied: colorama in c:\\programdata\\anaconda3\\lib\\site-packages (from ipython>=4.0.0->ipywidgets>=7->arcgis) (0.4.5)\n",
      "Requirement already satisfied: jedi>=0.16 in c:\\programdata\\anaconda3\\lib\\site-packages (from ipython>=4.0.0->ipywidgets>=7->arcgis) (0.18.1)\n",
      "Requirement already satisfied: setuptools>=18.5 in c:\\programdata\\anaconda3\\lib\\site-packages (from ipython>=4.0.0->ipywidgets>=7->arcgis) (63.4.1)\n",
      "Requirement already satisfied: pickleshare in c:\\programdata\\anaconda3\\lib\\site-packages (from ipython>=4.0.0->ipywidgets>=7->arcgis) (0.7.5)\n",
      "Requirement already satisfied: decorator in c:\\programdata\\anaconda3\\lib\\site-packages (from ipython>=4.0.0->ipywidgets>=7->arcgis) (5.1.1)\n",
      "Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in c:\\programdata\\anaconda3\\lib\\site-packages (from ipython>=4.0.0->ipywidgets>=7->arcgis) (3.0.20)\n",
      "Requirement already satisfied: MarkupSafe>=0.23 in c:\\programdata\\anaconda3\\lib\\site-packages (from jinja2->notebook->arcgis) (2.0.1)\n",
      "Requirement already satisfied: anyio<4,>=3.1.0 in c:\\programdata\\anaconda3\\lib\\site-packages (from jupyter-server~=1.16->jupyterlab->arcgis) (3.5.0)\n",
      "Requirement already satisfied: pywinpty in c:\\programdata\\anaconda3\\lib\\site-packages (from jupyter-server~=1.16->jupyterlab->arcgis) (2.0.2)\n",
      "Requirement already satisfied: websocket-client in c:\\programdata\\anaconda3\\lib\\site-packages (from jupyter-server~=1.16->jupyterlab->arcgis) (0.58.0)\n",
      "Requirement already satisfied: entrypoints>=0.2.2 in c:\\programdata\\anaconda3\\lib\\site-packages (from jupyterlab-server~=2.10->jupyterlab->arcgis) (0.4)\n",
      "Requirement already satisfied: babel in c:\\programdata\\anaconda3\\lib\\site-packages (from jupyterlab-server~=2.10->jupyterlab->arcgis) (2.9.1)\n",
      "Requirement already satisfied: jsonschema>=3.0.1 in c:\\programdata\\anaconda3\\lib\\site-packages (from jupyterlab-server~=2.10->jupyterlab->arcgis) (4.16.0)\n",
      "Requirement already satisfied: json5 in c:\\programdata\\anaconda3\\lib\\site-packages (from jupyterlab-server~=2.10->jupyterlab->arcgis) (0.9.6)\n",
      "Requirement already satisfied: jupyterlab-pygments in c:\\programdata\\anaconda3\\lib\\site-packages (from nbconvert>=5->notebook->arcgis) (0.1.2)\n",
      "Requirement already satisfied: beautifulsoup4 in c:\\programdata\\anaconda3\\lib\\site-packages (from nbconvert>=5->notebook->arcgis) (4.11.1)\n",
      "Requirement already satisfied: testpath in c:\\programdata\\anaconda3\\lib\\site-packages (from nbconvert>=5->notebook->arcgis) (0.6.0)\n",
      "Requirement already satisfied: mistune<2,>=0.8.1 in c:\\programdata\\anaconda3\\lib\\site-packages (from nbconvert>=5->notebook->arcgis) (0.8.4)\n",
      "Requirement already satisfied: pandocfilters>=1.4.1 in c:\\programdata\\anaconda3\\lib\\site-packages (from nbconvert>=5->notebook->arcgis) (1.5.0)\n",
      "Requirement already satisfied: nbclient<0.6.0,>=0.5.0 in c:\\programdata\\anaconda3\\lib\\site-packages (from nbconvert>=5->notebook->arcgis) (0.5.13)\n",
      "Requirement already satisfied: defusedxml in c:\\programdata\\anaconda3\\lib\\site-packages (from nbconvert>=5->notebook->arcgis) (0.7.1)\n",
      "Requirement already satisfied: bleach in c:\\programdata\\anaconda3\\lib\\site-packages (from nbconvert>=5->notebook->arcgis) (4.1.0)\n",
      "Requirement already satisfied: fastjsonschema in c:\\programdata\\anaconda3\\lib\\site-packages (from nbformat>=4.2.0->ipywidgets>=7->arcgis) (2.16.2)\n",
      "Requirement already satisfied: argon2-cffi-bindings in c:\\programdata\\anaconda3\\lib\\site-packages (from argon2-cffi->notebook->arcgis) (21.2.0)\n",
      "Requirement already satisfied: typing-extensions in c:\\users\\hp\\appdata\\roaming\\python\\python39\\site-packages (from setuptools-scm->python-certifi-win32->arcgis) (3.7.4.3)\n",
      "Requirement already satisfied: tomli>=1.0.0 in c:\\programdata\\anaconda3\\lib\\site-packages (from setuptools-scm->python-certifi-win32->arcgis) (2.0.1)\n",
      "Requirement already satisfied: sniffio>=1.1 in c:\\programdata\\anaconda3\\lib\\site-packages (from anyio<4,>=3.1.0->jupyter-server~=1.16->jupyterlab->arcgis) (1.2.0)\n",
      "Requirement already satisfied: parso<0.9.0,>=0.8.0 in c:\\programdata\\anaconda3\\lib\\site-packages (from jedi>=0.16->ipython>=4.0.0->ipywidgets>=7->arcgis) (0.8.3)\n",
      "Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in c:\\programdata\\anaconda3\\lib\\site-packages (from jsonschema>=3.0.1->jupyterlab-server~=2.10->jupyterlab->arcgis) (0.18.0)\n",
      "Requirement already satisfied: attrs>=17.4.0 in c:\\programdata\\anaconda3\\lib\\site-packages (from jsonschema>=3.0.1->jupyterlab-server~=2.10->jupyterlab->arcgis) (21.4.0)\n",
      "Requirement already satisfied: wcwidth in c:\\programdata\\anaconda3\\lib\\site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=4.0.0->ipywidgets>=7->arcgis) (0.2.5)\n",
      "Requirement already satisfied: soupsieve>1.2 in c:\\programdata\\anaconda3\\lib\\site-packages (from beautifulsoup4->nbconvert>=5->notebook->arcgis) (2.3.1)\n",
      "Requirement already satisfied: webencodings in c:\\programdata\\anaconda3\\lib\\site-packages (from bleach->nbconvert>=5->notebook->arcgis) (0.5.1)\n"
     ]
    }
   ],
   "source": [
    "!pip install arcgis"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "a8416f7b",
   "metadata": {},
   "outputs": [
    {
     "ename": "ImportError",
     "evalue": "cannot import name 'SpatialDataFrame' from 'arcgis.features' (C:\\Users\\HP\\AppData\\Roaming\\Python\\Python39\\site-packages\\arcgis\\features\\__init__.py)",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mImportError\u001b[0m                               Traceback (most recent call last)",
      "\u001b[1;32m~\\AppData\\Local\\Temp\\ipykernel_13676\\253074943.py\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m     12\u001b[0m \u001b[1;32mfrom\u001b[0m \u001b[0marcgis\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mgeoanalytics\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0muse_proximity\u001b[0m \u001b[1;32mimport\u001b[0m \u001b[0mcreate_buffers\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     13\u001b[0m \u001b[1;32mfrom\u001b[0m \u001b[0marcgis\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mgeoenrichment\u001b[0m \u001b[1;32mimport\u001b[0m \u001b[0menrich\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 14\u001b[1;33m \u001b[1;32mfrom\u001b[0m \u001b[0marcgis\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mfeatures\u001b[0m \u001b[1;32mimport\u001b[0m \u001b[0mSpatialDataFrame\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     15\u001b[0m \u001b[1;32mfrom\u001b[0m \u001b[0marcgis\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mraster\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0manalytics\u001b[0m \u001b[1;32mimport\u001b[0m \u001b[0mcreate_image_collection\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     16\u001b[0m \u001b[1;32mfrom\u001b[0m \u001b[0marcgis\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mraster\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0manalytics\u001b[0m \u001b[1;32mimport\u001b[0m \u001b[0mlist_datastore_content\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mImportError\u001b[0m: cannot import name 'SpatialDataFrame' from 'arcgis.features' (C:\\Users\\HP\\AppData\\Roaming\\Python\\Python39\\site-packages\\arcgis\\features\\__init__.py)"
     ]
    }
   ],
   "source": [
    "from datetime import datetime\n",
    "import warnings\n",
    "\n",
    "from IPython.display import HTML\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "\n",
    "import arcgis\n",
    "from arcgis import GIS\n",
    "from arcgis.raster.functions import *\n",
    "from arcgis.geoanalytics.use_proximity import create_buffers\n",
    "from arcgis.geoenrichment import enrich\n",
    "from arcgis.features import SpatialDataFrame\n",
    "from arcgis.raster.analytics import create_image_collection\n",
    "from arcgis.raster.analytics import list_datastore_content\n",
    "\n",
    "gis= GIS('https://pythonapi.playground.esri.com/portal', 'arcgis_python', 'amazing_arcgis_123')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ae9714d6",
   "metadata": {},
   "outputs": [],
   "source": [
    "list_datastore_content(\"C:\\Users\\HP\\Downloads\\dataset\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5169db80",
   "metadata": {},
   "outputs": [],
   "source": [
    "sentinel_collection = create_image_collection(image_collection=\"pawnee_fire_multispectral\",\n",
    "                      input_rasters=[\"C:\\Users\\HP\\Downloads\\dataset\\L1C_T43RDQ_A028488_20220820T054215\\S2B_MSIL1C_20220820T053649_N0400_R005_T43RDQ_20220820T073622.SAFE\",\n",
    "                                     \"C:\\Users\\HP\\Downloads\\dataset\\L1C_T43RDQ_A028631_20220830T054109\\S2B_MSIL1C_20220830T053639_N0400_R005_T43RDQ_20220830T074358.SAFE\"],\n",
    "                      raster_type_name=\"Sentinel-2\", \n",
    "                      raster_type_params={\"productType\":\"All\",\"processingTemplate\":\"Multispectral\"},\n",
    "                      context={\"image_collection_properties\":{\"imageCollectionType\":\"Satellite\"},\"byref\":True}, gis = gis)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
